class CreateHgtParFragms < ActiveRecord::Migration
  
  def up
   
    create_table :hgt_par_fragms do |t|
      t.references :gene
      t.references :hgt_par_contin
      #specific to partial transfers
      t.integer :fen_no
      t.integer :fen_idx_min
      t.integer :fen_idx_max
      #also in complete transfer
      t.integer :iter_no
      t.integer :hgt_no
      t.string :hgt_type
      t.string :from_subtree, :limit => 16777216 #like longvarchar
      t.integer :from_cnt
      t.string :to_subtree, :limit => 16777216 #like longvarchar
      t.integer :to_cnt
      t.float :bs_val
      #absolute values for partial, 
      #relative values in complete
      t.float :bs_direct
      t.float :bs_inverse
      #realign status
      t.string :contin_realign_status
      

      t.timestamps
    end
    add_index :hgt_par_fragms, :gene_id
    add_index :hgt_par_fragms, :hgt_par_contin_id
    

    
  end
  
  def down
    drop_table :hgt_par_fragms
    
  end
  
=begin  

    #assure longvarchar
    #sql = "alter table HGT_PAR_FRAGMS alter column from_subtree set data type longvarchar;"
    #ActiveRecord::Base.connection.execute(sql)
    
    #sql = "alter table HGT_PAR_FRAGMS alter column to_subtree set data type longvarchar;"
    #ActiveRecord::Base.connection.execute(sql)

  def up
    sql = "CREATE TABLE hgt_par_fragms (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
    gene_id integer,
    fen_no integer,
    fen_idx_min integer,
    fen_idx_max integer,
    iter_no integer,
    hgt_no integer,
    hgt_type varchar(255),
    from_subtree longvarchar,
    from_cnt integer,
    to_subtree longvarchar,
    to_cnt integer,
    bs_val float,
    bs_direct float,
    bs_inverse float,
    created_at DATETIME,
    updated_at DATETIME
    );"
    ActiveRecord::Base.connection.execute(sql)
    
    sql = "CREATE INDEX index_hgt_par_fragms_on_gene_id ON hgt_par_fragms (gene_id);"
    ActiveRecord::Base.connection.execute(sql)
  end

  def down
    sql = "drop table hgt_par_fragms;"
    ActiveRecord::Base.connection.execute(sql)
  end

=end

  

   
  
  
=begin  
    sql = "CREATE TABLE hgt_par_fragms (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
    gene_id integer,
    fen_no integer,
    fen_idx_min integer,
    fen_idx_max integer,
    iter_no integer,
    hgt_no integer,
    hgt_type varchar(255),
    from_subtree clob,
    from_cnt integer,
    to_subtree clob,
    to_cnt integer,
    bs_val float,
    bs_direct float,
    bs_inverse float,
    created_at DATETIME,
    updated_at DATETIME
    );"
    ActiveRecord::Base.connection.execute(sql)
  
=end
end
