CREATE FUNCTION size_by_group_gene(IN P1 INT) 
RETURNS TABLE(C1 INT) 
SPECIFIC F1 LANGUAGE JAVA DETERMINISTIC 
EXTERNAL NAME 'CLASSPATH:proc_hom_sp.HgtPar.sizeByGroupGene'

call SIZE_BY_GROUP_GENE(1);

call SIZE_BY_GROUP_GENE(1);


call SIZE_BY_GROUP_GENE(1, 'x');

drop function size_by_group_gene

drop table mytable

CREATE PROCEDURE proc1(IN P1 INT, IN P2 INT, OUT P3 INT) 
SPECIFIC P2 LANGUAGE JAVA DETERMINISTIC MODIFIES SQL DATA EXTERNAL NAME 'CLASSPATH:proc_hom_sp.HgtPar.procTest2'